apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /share/gitlab
    server: 192.168.88.12
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
